# ===============================
# SERVER (Render ke liye IMPORTANT)
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE (H2 - deploy friendly)
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# ===============================
# EMAIL (Demo ke liye ok)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=avishkarkalel121@gmail.com
spring.mail.password=jdkjijseyltygcip
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true